djangoProject2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from djangoProject2 import settings
from sacco import views

urlpatterns = [

    path('', views.customers, name='customers'),
    path('add/customer', views.add_customer, name='add_customer'),
    path('customer/delete/<int:customer_id>', views.delete_customer, name='delete_customer'),
    path('customer/details/<int:customer_id>', views.customer_details, name='customer_details'),
    path('customer/Update/<int:customer_id>', views.update_customer, name='update_customer'),
    path('customer/Deposits/<int:customer_id>', views.deposit, name='deposit'),
    path('customer/Search', views.search_customer, name='search_customer'),
    path('login', views.login_user, name='login'),
    path('logout', views.signout_user, name='logout'),



    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#line 25 used to delete

sacco/models.py
import os

import uuid


from uuid import uuid4

from django.db import models


def generate_unique_name(instance, file_name):
    name = uuid.uuid4()
    full_file_name =f"{name}-{file_name}"
    return os.path.join("profile_pic", full_file_name)



class Customer(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    dob = models.DateField()
    gender = models.CharField(max_length=10)
    weight = models.IntegerField(default=0)
    profile_pic = models.ImageField(upload_to=generate_unique_name, null=True ) # holds the image field
    created_at = models.DateTimeField(auto_now_add=True)  # to show when it was created
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name}  {self.last_name} {self.gender}"  #shows in django admin f,l,g

    class Meta:
        db_table = 'customers'


class Deposit(models.Model):

    amount = models.IntegerField()
    status = models.BooleanField(default=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer.first_name} - {self.amount}"


    class Meta:
        db_table = 'deposits'

#python manage.py makemigrations
        #python manage.py populate
        #python manage.py migrate

sacco/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q, Sum
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from sacco.app_forms import CustomerForm, DepositForm, LoginForm
from sacco.models import Customer, Deposit


# Create your views here.
def test(request):
    # c1 = Customer(first_name='John', last_name='Smith',email='j@gmail.com',dob='2000-11-22',gender='Male',weight=63.5)
    # c1.save()
    #
    # c2 = Customer(first_name='Jack', last_name='Smen', email='alan@gmail.com', dob='2001-12-22', gender='Male',
    #               weight=62.5)
    # c2.save()

    # fetching one customer
    customers_count = Customer.objects.count()
    c1 = Customer.objects.get(id=1)  # select*from customers where id=1
    print(c1)

    d1 = Deposit(amount=1000, status=True, customer=c1)
    d1.save()
    deposit_count = Deposit.objects.count()


    return HttpResponse(f"Hello World the {customers_count} Customers are listed here and their{deposit_count} Deposits are listed here")
#the below import ensures no one can view information without login in
@login_required
def customers(request):
    data = Customer.objects.all().order_by('id').values()   # select*from all orm object relational mapper. -id means in descending orderwhile id is in ascending order
    paginator = Paginator(data, 15)  #this one separets the data in pages
    page_number = request.GET.get('page', 1)
    try:
        paginated_data = paginator.page(page_number)
    except PageNotAnInteger |EmptyPage:
        paginated_data = paginator.page(1)
    return render(request, "customers.html", {"data": paginated_data})

@login_required
@permission_required("Sacco.delete_customer",raise_exception=True)
def delete_customer(request,customer_id):
    customer = Customer.objects.get(id=customer_id)
    customer.delete()   # delete where id =7
    messages.info(request, f"customer {customer_id} has been deleted")
    return redirect('customers')


# line 34 deleting customer in views file.
@login_required
@permission_required("Sacco.add_customer",raise_exception=True)
def add_customer(request):
    if request.method == "POST":
      form = CustomerForm(request.POST,request.FILES)
      if form.is_valid():
          form.save() # saves customer and redirects to home page
          messages.success(request, f"Customer {form.cleaned_data['first_name']} has been added")
          return redirect('customers')
    else:
        form = CustomerForm()
    return render(request,'customer_form.html',{"form":form})


@login_required
@permission_required("Sacco.change_customer", raise_exception=True)
def update_customer(request,customer_id):
    customer = get_object_or_404(Customer,id=customer_id)
    if request.method == "POST":
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()  # saves customer and redirects to home page
            messages.success(request, f"Customer {form.cleaned_data['first_name']} was updated")
            return redirect('customers')
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'customer_update_form.html', {"form": form})


@login_required
@permission_required("Sacco.view_customer", raise_exception=True)
def search_customer(request):
    search_term = request.GET.get('search')
    data = Customer.objects.filter(Q(first_name__icontains=search_term) | Q(last_name__icontains=search_term) | Q(email__icontains=search_term))
    #select* from customers where first name is like %noel% or last_name like
    return render(request, "search.html", {"customers": data})



@login_required
@permission_required("Sacco.add_customer",raise_exception=True)
def deposit(request,customer_id):
    customer = get_object_or_404(Customer,id=customer_id)
    if request.method == "POST":
        form = DepositForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            depo = Deposit(amount=amount, status=True, customer=customer)
            depo.save()
            messages.success(request,'Your deposited have been successfully saved.') # import from django contrib messages
            return redirect('customers')
    else:
        form = DepositForm()
    return render(request, template_name= 'customer_form_deposits.html', context={"form": form, "customer": customer})

@login_required
@permission_required("Sacco.view_customer",raise_exception=True)
def customer_details(request,customer_id):
    customer = Customer.objects.get(id=customer_id)
    deposits = Deposit.objects.filter(customer_id=customer_id)
    total = Deposit.objects.filter(customer=customer).filter(status=True).aggregate(Sum('amount'))["amount__sum"]
    return render(request,template_name="details.html", context={"deposits": deposits ,"customer": customer ,"total": total })




# beautifies the form using bootstrap use in terminal
# pip install django-crispy-forms
#pip install crispy-bootstrap5
# line 43 and 44 saves data
#pip install Pillow


def login_user(request):
    if request.method == "GET":
       form = LoginForm
       return render(request,'login_form.html',{"form":form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
           username = form.cleaned_data['username']
           password = form.cleaned_data['password']
           user = authenticate(request, username=username,password=password)
           if user:
                login(request, user) # sessions,cookies
                return redirect('customers')
           messages.error(request, 'Invalid username or password.')
           return render(request,template_name= "login_form.html", context={"form":form})

@login_required
def signout_user(request):
    logout(request)
    return redirect('login')

templates/customer_form.html
{% extends 'master.html' %}
{% load crispy_forms_filters %}


{% block title %}
	<title>Add Customer</title>
{% endblock %}


{% block content %}
	<div class="container">
   <div class="row justify-content-center">
       <div class="col-sm-4 border px-3 py-3 mt-3"> {% comment %}px-3 is padding to the x axis py-3 is padding to y axis{% endcomment %}
           {% comment %} use django classes post for secured data and get does not make data secured{% endcomment %}
           <form action="{% url 'add_customer' %}" method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form | crispy }}
               <button class="btn btn-primary w-100">Save Customer</button>
           </form>
       </div>
   </div>
    </div>
{% endblock %}

templates/customer_form_deposits.html
{% extends 'master.html' %}
{% load crispy_forms_filters %}


{% block title %}
	<title>Add Deposits</title>
{% endblock %}


{% block content %}
	<div class="container">
   <div class="row justify-content-center">
       <div class="col-sm-4 border px-3 py-3 mt-3"> {% comment %}px-3 is padding to the x axis py-3 is padding to y axis{% endcomment %}
           {% comment %} use django classes post for secured data and get does not make data secured{% endcomment %}
           <h3>Name:{{ customer.first_name}} {{ customer.last_name}}</h3>
           <p>Email:{{ customer.email }}</p>
           <p>Joining Date:{{ customer.created_at | date:"d-m-Y" }}</p>
           <form action="" method="post">
               {% csrf_token %}
               {{ form | crispy }}
               <button class="btn btn-dark w-100">Save Deposits</button>
           </form>
       </div>
   </div>
    </div>
{% endblock %}

templates/customer_update_form.html
{% extends 'master.html' %}
{% load crispy_forms_filters %}


{% block title %}
	<title>Update Customer</title>
{% endblock %}


{% block content %}
	<div class="container">
   <div class="row justify-content-center">
       <div class="col-sm-4 border px-3 py-3 mt-3"> {% comment %}px-3 is padding to the x axis py-3 is padding to y axis{% endcomment %}
           {% comment %} use django classes post for secured data and get does not make data secured{% endcomment %}
           <form action="" method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form | crispy }}
               <button class="btn btn-success w-100">Update Customer</button>
           </form>
       </div>
   </div>
    </div>
{% endblock %}


{% comment %} this is the form to update which is completely the same as customer form just copy and paste then change the adds to update as step1
 step 2 go to url.py {% endcomment %}

templates/customers.html
{% extends 'master.html' %}

{% block title %}
	<title>Sacco Customers</title>
{% endblock %}


{% block content %}
	<div class="container">
    <h2>Sacco Customers.</h2>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Joining Date</th>
            {% if  perms.Sacco.delete_customer %}
            	<th> Delete</th>
            {% endif %} 
            {% if  perms.Sacco.change_customer %}
            	 <th> Update</th>
            {% endif %} 
            {% if  perms.Sacco.add_deposit %}
            	 <th> Deposit</th>
            {% endif %} 
            {% if  perms.Sacco.view_customer %}
            <th> Details</th>
            {% endif %} 
            
            
            
            
           
            <th> Details</th>
        </tr>
    
        {% for customer in data.object_list %}   {% comment %}click fore then control space and choose the second option{% endcomment %}  
        	<tr>
                <td>{{ customer.id }}</td>
                <td>{{ customer.first_name }}</td>
                <td>{{ customer.last_name}}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.created_at |date:"d-m-Y" }}</td>
                {% if perms.Sacco.delete_customer %}
                	<td>
                    <a class ="btn btn-primary btn-sm " href="{% url 'delete_customer' customer.id %}" >Remove</a>
                </td>
                {% endif %} 
                {% if perms.Sacco.change_customer %}
                	 <td>
                    <a class ="btn btn-success btn-sm" href="{% url 'update_customer' customer.id %}" >Update</a>
                </td>
                {% endif %} 
               {% if perms.Sacco.add_deposit %}
                	 <td>
                    <a class ="btn btn-dark btn-sm" href="{% url 'deposit' customer.id %}" >Deposit</a>
                </td>
                {% endif %} 
               {% if perms.Sacco.view_customer %}
                	  <td>
                    <a class ="btn btn-danger btn-sm" href="{% url 'customer_details' customer.id %}" >Details</a>
                </td>
                {% endif %} 
                
           
            
           
            </tr>
        {% empty %}
        	<p>No Customers In the Sacco</p>
        {% endfor %}
        
    </table>
    <div class="row justify-content-center">
        <div class="col-sm-2">
            {% if data.has_previous %}
                <a class="btn btn-outline-info btn-sm"  href="?page={{ data.previous_page_number }}"> << </a>
            	
            {% endif %} 
            <span class="mx-3">{{ data.number }}</span>
            {% if data.has_next %}
                <a class="btn btn-outline-info btn-sm" href="?page={{ data.next_page_number }}"> >> </a>
            {% endif %} 
            
        </div>
    </div>
    </div>
{% endblock %}

templates/details.html
{% extends 'master.html' %}

{% load static %}

{% block title %}
	<title>Customer Details</title>
{% endblock %}




{% block content %}
	<div class="container">
    <div class="row mt-2">
        <div class="col-sm-4 mt-3">
            <table class="table table-striped">
                <tr>
                    <td class="h6">First Name</td>
                    <td> {{ customer.first_name }}</td>
                </tr>
                 <tr>
                    <td class="h6">Last_Name</td>
                    <td> {{ customer.last_name }}</td>
                </tr>
                 <tr>
                    <td class="h6">Email</td>
                    <td> {{ customer.email}}</td>
                </tr>
                 <tr>
                    <td class="h6">Date of Birth</td>
                    <td> {{ customer.dob |date:"d-m-Y" }}</td>
                </tr>
                 <tr>
                    <td class="h6">Gender</td>
                    <td> {{ customer.gender }}</td>
                </tr>
                 <tr>
                    <td class="h6">Weight in Kg</td>
                    <td> {{ customer.weight }}</td>
                </tr>
                <tr>
                    <td class="h6">Total Deposit</td>
                    <td>{{total}}</td>
                </tr>
            </table>
        </div>
        <div class="col-sm-4">
            <p class="text-center">Profile Picture</p>
           
            {% if customer.profile_pic %}
               	 <img class="img-fluid mx-auto d-block profile" src="{{ customer.profile_pic.url }}" alt="">
            {% else %}
               	 <img class="img-fluid mx-auto d-block profile" src="{% static 'profile.png' %}" alt="">
            {% endif %} 
        </div>
        <div class="col-sm-4">
            <table class="table table-bordered">
                <tr>
                    <th>Date</th>
                    <th>Deposit</th>
                    <th>Status</th>
                </tr>
                {% for depo in deposits %}
                    <tr>
                        <td>{{ depo.created_at | date:"d-m-Y" }}</td>
                        <td>{{ depo.amount }}</td>
                        <td>{{ depo.status }}</td>
                    </tr>
                	
                {% endfor %}
                
            </table>
        </div>
    </div>
    </div>
{% endblock %}


{% comment %} python manage.py collectstatic
 loads image in terminal{% endcomment %}

{% comment %}#pip install Pillow
  to load clients image then go to models{% endcomment %}

templates/login_form.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% comment %} vh-100 it fits the whole page,jcc-centers horizontantally ,aic-centers vertically{% endcomment %}
<div class=" vh-100 d-flex justify-content-center align-items-center">
    <div class="row justify-content-center w-100">
        <div class="col-sm-4">
            {% comment %}post hides password on link while searching get displays it{% endcomment %}
            <form action="{% url 'login' %}" method="post" class="shadow px-3 py-4">
                {% csrf_token %} {% comment %}ensures its our data{% endcomment %}
                {{ form | crispy }}
                <button class="btn btn-dark rounded-0 w-100 "> {% comment %} rounded-0 has 90 degree curves{% endcomment %}
                    Sign In
                </button>
            </form>
        </div>
    </div>
</div>























<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Sacco.</title>
    {% endblock %}
    {#    bootstrap css#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        legend {
            font-size: 1rem;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="">Umoja Sacco</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers' %}">Customers</a>
                </li>
                <li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_customer' %}">Add Customer</a>
                </li>
                <a class="nav-link" href="#">Statistics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Transactions</a>
                </li>
            </ul>
            <form class="d-flex" method="get" action="{% url 'search_customer' %}">
                <input class="form-control me-2" type="text" name="search" placeholder="Search">
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container">
    {% for message in messages  %}
        <div class="alert {{ message.tags }} alert-dismissible fade show mt-3" role="alert">
        <p>{{ message }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    
  
</div>
{% block content %}

{% endblock %}






<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/search.html
{% extends 'master.html' %}

{% block title %}
	<title>Sacco Customers</title>
{% endblock %}


{% block content %}
	<div class="container">
    <h2>Search Results</h2>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Joining Date</th>
            <th> Delete</th>
             <th> Update</th>
        </tr>
    
        {% for customer in customers %}   {% comment %}click fore then control space and choose the second option{% endcomment %}  
        	<tr>
                <td>{{ customer.id }}</td>
                <td>{{ customer.first_name }}</td>
                <td>{{ customer.last_name}}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.created_at }}</td>
                <td>
                    <a class ="btn btn-primary " href="{% url 'delete_customer' customer.id %}" >Remove</a>
                </td>
            <td>
                    <a class ="btn btn-success " href="{% url 'update_customer' customer.id %}" >Update</a>
                </td>
            </tr>
        {% empty %}
        	<p>No Customers found</p>
        {% endfor %}
        
    </table>
    </div>
{% endblock %}